### ISSUE TITLE
Add info regarding plots incompatibility in the ReadMe

### ISSUE THREAD

**Issue by ageorge95** [Achi-Coin/achi-blockchain#10]
As the title says, please add this info in the ReadMe. I lost some time debugging why I cannot farm, only to find out that custom plots are needed from Discord ...

**Comment by Achi-Coin** [comment]
https://achicoin.org/faq/

**Comment by ageorge95** [comment]
The purpose of this issue was to add this info in ReadMe. Nobody checks the FAQ first.

But anyway, it is your coin do what you want with it :)

**Comment by Achi-Coin** [comment]
done
