### ISSUE TITLE
very very very long and slow synchronisation Ubuntu 20.04

### ISSUE THREAD

**Issue by dipol0** [Achi-Coin/achi-blockchain#12]
very low synch on Ubnuntu 20.04/ Port 9975 portforwarded. See UP/DOWN.

Router very normal. Port 9975 forwarded/
CPU Intel i7-7700k,
RAM 32gb
OS Ubuntu 20.0.4 (clean)
Python 3.8.10
Achi version1.0.3 (build from git)

**achi show -c:**

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
TIMELORD  127.0.0.1                              60730/9810  51a42334... Sep 19 03:05:42      0.0|0.0    
FARMER    127.0.0.1                              60732/9977  50ad0fb5... Sep 19 03:05:42      0.0|0.0    
FULL_NODE 3                            9975/9975  74174602... Sep 19 09:15:30      0.0|4.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 7                          59526/9975  b9c2acdf... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 3                           59254/9975  b2c5551f... Sep 19 09:15:31      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE  2                         63232/9975  3b8e3f34... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .1                           50643/9975  dbbde222... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 6                          50338/9975  11da3fb8... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .116                          1465/9975  54f9584a... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .44                         61990/9975  1eda5057... Sep 19 09:15:30      0.0|0.1    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .222                         36967/9975  96d80731... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 62                           33884/9975  16647c61... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 231                         52864/9975  5a45338b... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 127                            4677/9975  b64659ea... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 1.8                           57650/9975  b0de2cb3... Sep 19 09:10:37      0.0|0.0    
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 15                        16143/9975  31cbdff5... Sep 19 08:45:42      0.0|0.0    
                                                 -SB Height:    69920    -Hash: 02597728...
FULL_NODE 28                        65516/9975  105055db... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 75                           54696/9975  32337948... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 2                            9975/9975  8ed15bb8... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 3                           45218/9975  6a5c99da... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 0                         49518/9975  f641d610... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 32                            42730/9975  c11e57dc... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 0                          38008/9975  f94560df... Sep 19 08:49:44      0.0|0.0    
                                                 -SB Height:   122208    -Hash: 617cbf58...
FULL_NODE 2                          52863/9975  ff475f20... Sep 19 08:50:43      0.0|0.0    
                                                 -SB Height:    26816    -Hash: 2f29740e...
FULL_NODE 38                        51517/9975  1883de8f... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 9                           57426/9975  a9e1874d... Sep 19 08:52:09      0.0|0.0    
                                                 -SB Height:    15872    -Hash: 1433c1d6...
FULL_NODE 98                           32288/9975  506d8ccf... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 46                          63936/9975  73538976... Sep 19 08:58:25      0.0|0.0    
                                                 -SB Height:    50720    -Hash: 5cf3ef7c...
FULL_NODE 162                          2146/9975  f1c457e7... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .49                          60019/9975  076ddbdf... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 3.247                        43498/9975  9e307be7... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .44                            9975/9975  25e21fe9... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 8.102                         32591/9975  d9d5b115... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 35.46                          55986/9975  ac783d24... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .31                           43180/9975  c051b2fa... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 8.153                        55908/9975  517db9c3... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 19.166                         9975/9975  27101e7d... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 6.163                         52319/9975  ad7b3438... Sep 19 09:04:13      0.0|0.0    
                                                 -SB Height:   135712    -Hash: d0411571...
FULL_NODE 6.102                         9975/9975  482e3dcf... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 5.49                          19502/9975  11918590... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .115                          56917/9975  14bdd7ac... Sep 19 09:07:07      0.0|0.0    
                                                 -SB Height:   143678    -Hash: 5574610e...
FULL_NODE 8.37                           2073/9975  fdc41ad2... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 6.153                         13296/9975  69331ff3... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE .66                            9975/9975  dcb5cbb0... Sep 19 09:15:31      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 0.251                         51119/9975  b0edea54... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 702.100                          3203/9975  8d34a1db... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
FULL_NODE 2.205                          9975/9975  837b112e... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...
WALLET    127.0.0.1                              60954/9935  24f4c993... Sep 19 09:15:18     15.3|0.0    
FULL_NODE 1.69                            9975/9975  40d894d3... Sep 19 09:15:30      0.0|0.0    
                                                 -SB Height:   180138    -Hash: 1d3f62dc...

and after few **achi show -s** with time period show only sync to Block NNN (30000 for exemple). Only restart all achi show what sync continued slowly.

same time achi show -s show this:

_Exception from 'show' Traceback (most recent call last):
  File "/home/manager/src/achi-blockchain/achi/cmds/show.py", line 40, in show_async
    blockchain_state = await client.get_blockchain_state()
  File "/home/manager/src/achi-blockchain/achi/rpc/full_node_rpc_client.py", line 24, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/home/manager/src/achi-blockchain/achi/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/home/manager/src/achi-blockchain/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/manager/src/achi-blockchain/venv/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/manager/src/achi-blockchain/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/home/manager/src/achi-blockchain/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError_

+++
and i thin achi show -s dont update sync info correctly. you can run it few times with long period but get every time what you stay on same place. For examle^

_Current Blockchain Status: Full Node syncing to block 180464_

But after ACHI START -R ALL info update one time and repeat... until you dont restart achi....

checked on versions 1.0.2 and 1.0.3

Help! )) The train leaves for the moon but iam stay here.

**Comment by Achi-Coin** [comment]
Hi! Check your system time!

**Comment by dipol0** [comment]
iam have router synced time with ntp.org and PC have ntp-client and synch time from this router


> Hi! Check your system time!

I have router synced time with ntp.org and PC have ntp-client and synch time from this router. Today my PC shutdown 3h after i power on PC all repeat ... synching vary slowly...

LOG

[debug.log](https://github.com/Achi-Coin/achi-blockchain/files/7206304/debug.log)
