### ISSUE TITLE
achi_plot.exe crashed in windows 10 x64 ，please check

### ISSUE THREAD

**Issue by Fwar** [Achi-Coin/achi-blockchain#15]

**Comment by Fwar** [comment]
![1632377277(1)](https://user-images.githubusercontent.com/74693723/134461321-a2c9f102-cc2b-4fdc-a217-a7c993800dda.png)
I try change different pc , it's also crashed.

**Comment by Achi-Coin** [comment]
Try new fixed version  https://download.achicoin.org/achi_plot_beta.zip
