### ISSUE TITLE
How to start Timelord properly

### ISSUE THREAD

**Issue by ag3ntt** [Achi-Coin/achi-blockchain#2]
Hi @Achi-Coin,

I have 16 core CPU (AMD Ryzen 5950X) with 128 GB RAM, so I want to provide Timelord for Achi.

How to run Timelord properly? I have timelord service enabled, also I have destination-NAT for port 9975 on my public IP. Logs are full of some Timelord activities, but I don't see any rewards related to 0.02%/block for working Timelord.

Probably there are some next requirements?

**Comment by Achi-Coin** [comment]
Hello Ag3ntt!

Your setup is absolutely correct.
Final step to make your Timelord rewaded is ro define DEFAULT_CONSTANTS.TIMELORD_PUZZLE_HASH. Add reward_puzzle_hash to config.yaml. For example:
timelord:
   reward_puzzle_hash:
     59ae00d2jhlkjhkjlhads34fhjklaerr34eerhd34skjfhkj43543dsahfjkhhh87y873

Please bear in mind that reward goes to the fastest timelord in the network. Use command vdf_bench square_asm 400000 to check computation speed of your timelord.

Good luck!

**Comment by ag3ntt** [comment]
Thank you, @Achi-Coin.

What is value for `reward_puzzle_hash`? Where I can take it?

Btw, result of my `./vdf_bench square_asm 400000` is:

```
Time: 1889 ms; n_slow: 74; speed: 211.7K ips
a = 0x6ce27bdb0240cadd4f5ba8eda519bfbe0ffd5ad3004ff27b9d6f65c62815265730bce32258434615674124e204f3c3429e6c214fd171846f5c0acf27c754ac42
b = -0x2040323dc47947c6161535b2e1366a274671d9bd1f9cb7644cb0da6b237a886a8414c9d9fa33f3fd9d9072b34561bc51e93ec1fbb341f6a18de5dd5c63fa421f
c = 0x78869cb37a6a7d392b19000ce9dc30358093871a2753ea79c0cabe40e283d1a2f60234c2f2f8777fde662a87f55a4cb7fea3489750e83c9cefff52fc594b19ab`
```

**Comment by ag3ntt** [comment]
I think that i got it :)

Reward puzzle hash can be generated by commands below (you need your achi wallet address). For chia (but not for an achi) there is a tool https://www.chiaexplorer.com/tools/address-puzzlehash-converter

```bash
cd /path/to/achi-blockchain/
. ./activate
python -c 'import achi.util.bech32m as b; print(b.decode_puzzle_hash("HERE-YOUR-ACHI-WALLET-ADDRESS").hex())'
```
