### ISSUE TITLE
incorrect data in Height

### ISSUE THREAD

**Issue by frankfurtru** [Achi-Coin/achi-blockchain#8]
1) Run **achi farm summary**
1.1) See field Last height farmed: **69689**
2) Run **achi show -s**
2.1) See field Height: **70598**

Digits are different: Last height farmed != Height

**Comment by frankfurtru** [comment]
I thought if node is fully synced: Last height farmed == Height
Could you clarify please:))

**Comment by Achi-Coin** [comment]
Last height FARMED - by your node,
HIGHT is current last block of blockchain
