### ISSUE TITLE
Issue with "Farming status: Not synced or not connected to peers"

### ISSUE THREAD

**Issue by dzhechko** [Achi-Coin/achi-blockchain#9]
Hello !

I have deployed a couple of achi nodes: one on aws EC2 (it works well) and another one in local data center on bare metal server. With Bare Metal I have a problem the output of "achi show -s" is "Current Blockchain Status: Not Synced."
achi show -s
Current Blockchain Status: Not Synced. Peak height: 90593
      Time: Tue Aug 31 2021 19:19:54 UTC                  Height:      90593

Estimated network space: 1.136 PiB
Current difficulty: 39
Current VDF sub_slot_iters: 114819072
Total iterations since the start of the blockchain: 302354226280

All achi services are up and running:
ps -ef | grep achi
root        6028       1  0 22:03 pts/2    00:00:02 achi_daemon
root        6241    6028  0 22:03 pts/2    00:00:02 achi_harvester
root        6242    6028  0 22:03 pts/2    00:00:02 achi_farmer
root        6243    6028  3 22:03 pts/2    00:00:34 achi_full_node
root        6244    6028  1 22:03 pts/2    00:00:17 achi_wallet
root        6698    6243  0 22:03 pts/2    00:00:02 achi_full_node
root        6699    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6700    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6701    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6702    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6703    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6704    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6705    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6706    6243  0 22:03 pts/2    00:00:01 achi_full_node
root        6707    6243  0 22:03 pts/2    00:00:01 achi_full_node

achi show -c
Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
FARMER    127.0.0.1                              54964/9977  806a6286... Aug 31 22:11:03      0.0|0.0    
WALLET    127.0.0.1                              54974/9935  3f67742c... Aug 31 22:22:50      0.4|0.0    
FULL_NODE 178.63.218.79                           9975/9975  c67fb460... Aug 31 22:23:09      0.0|0.3    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 207.38.166.168                          9975/9975  52a19fba... Aug 31 22:23:09      0.1|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 45.80.181.69                            9975/9975  40d894d3... Aug 31 22:23:10      0.1|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 222.253.52.249                          9975/9975  c642a5db... Aug 31 22:23:10      0.1|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 82.146.50.31                            9975/9975  c051b2fa... Aug 31 22:23:09      0.0|0.4    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 168.119.149.166                         9975/9975  27101e7d... Aug 31 22:23:09      0.0|0.2    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 170.249.236.56                          9975/9975  c0f7aea0... Aug 31 22:23:10      0.0|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 31.220.60.142                           9975/9975  87e39628... Aug 31 22:23:09      0.0|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...
FULL_NODE 222.121.47.122                         46172/9975  11395623... Aug 31 22:23:10      0.2|0.0    
                                                 -SB Height:    90599    -Hash: ed32a1ac...

The working node in AWS has similar outputs, but it synchronized.
Could you please help me to troubleshoot the problem with Bare Metal ? 
It has been in "Farming status: Not synced or not connected to peers" for 3 days now 
Thank you for your support!

Kind regards,
Dmitry

**Comment by Achi-Coin** [comment]
Hi! it is difficult to troubleshoot your problem without log.
Can you please send debug log?

'achi configure --set-log-level DEBUG'
'achi start -r farmer'

**Comment by dzhechko** [comment]
Hi! Thank you for your prompt reply, please find the logs here https://dropmefiles.com/NODCb

**Comment by Achi-Coin** [comment]
Thanks for the log! I'd recommend the following
- Stop your aws EC2 (which works well) and copy db blockchain_v1_mainnet.sqlite to bare metal server.
- Synchronization should be faster.
- It's better to create another user, do not start as root.
If it does not help, try to re-install everything from scratch following instruction https://achicoin.org/achipedia/post-1/

**Comment by dzhechko** [comment]
Thank you very much for your reply ! Will proceed as you suggested and will update on the results soon !

**Comment by dzhechko** [comment]
copy of blockchain_v1_mainnet.sqlite did not help up until now - will leave it till tomorrow and will do re-install if will not sync

**Comment by dzhechko** [comment]
re-install of Ubuntu helped to solve the problem with node synchronisation

**Comment by Achi-Coin** [comment]
Well done!
